"""add executions

Revision ID: 3e45336da9d1
Revises: 3bb49eff60fb
Create Date: 2026-09-24 18:51:23.822719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e45336da9d1'
down_revision: Union[str, None] = '3bb49eff60fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_queue', 'executions', ['status', 'available_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('ix_executions_running_locked_at', 'executions', ['locked_at'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_index('ix_executions_workflow_created_at', 'executions', ['workflow_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_workflow_created_at', table_name='executions')
    op.drop_index('ix_executions_running_locked_at', table_name='executions', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('ix_executions_queue', table_name='executions', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('executions')
    # ### end Alembic commands ###
