"""add execution steps and version pin

Revision ID: 64566e54d37f
Revises: 3e45336da9d1
Create Date: 2026-09-24 19:14:35.596821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '64566e54d37f'
down_revision: Union[str, None] = '3e45336da9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_steps_execution_id', 'execution_steps', ['execution_id'], unique=False)
    op.create_index('ix_execution_steps_idempotency_key', 'execution_steps', ['idempotency_key'], unique=False)
    op.add_column('executions', sa.Column('workflow_version_id', sa.Uuid(), nullable=False))
    op.add_column('executions', sa.Column('trigger_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # имя FK задано явно: autogenerate оставлял None, и downgrade падал бы на
    # безымянном drop_constraint (тот же урок, что с circular FK в 3.A)
    op.create_foreign_key(
        'executions_workflow_version_id_fkey',
        'executions', 'workflow_versions', ['workflow_version_id'], ['id'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('executions_workflow_version_id_fkey', 'executions', type_='foreignkey')
    op.drop_column('executions', 'trigger_payload')
    op.drop_column('executions', 'workflow_version_id')
    op.drop_index('ix_execution_steps_idempotency_key', table_name='execution_steps')
    op.drop_index('ix_execution_steps_execution_id', table_name='execution_steps')
    op.drop_table('execution_steps')
    # ### end Alembic commands ###
