"""add trigger_type to executions

Revision ID: 941bceee1ad2
Revises: 64566e54d37f
Create Date: 2026-09-24 20:03:58.552709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '941bceee1ad2'
down_revision: Union[str, None] = '64566e54d37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default обязателен: без него add_column на непустой таблице падает,
    # т.к. существующие строки не получают значение для NOT NULL
    op.add_column(
        'executions',
        sa.Column('trigger_type', sa.String(), nullable=False, server_default='manual'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'trigger_type')
    # ### end Alembic commands ###
